// SPDX-FileCopyrightText: © 2025 SRAM Forge Contributors
// SPDX-License-Identifier: Apache-2.0
// Generated by sram-forge
// Chip: gf180mcu_ic_1x0p5_sram_u8b9k
// GF180MCU 1x0.5 SRAM Test Chip - 9KB unified 8-bit bus
// Configuration:
//   SRAM Macro: gf180mcu_fd_ip_sram__sram512x8m8wm1
//   Total SRAMs: 18
//   Total Words: 9216
//   Address Bits: 14
//   Data Width: 8
//   Output Routing: mux

`default_nettype none

module gf180mcu_ic_1x0p5_sram_u8b9k_sram_array (
    `ifdef USE_POWER_PINS
    // Power supplies (directly connected to SRAM macros)
    inout  wire                    VDD,
    inout  wire                    VSS,
    `endif
    // Functional signals
    input  wire                    clk,
    input  wire                    rst_n,
    input  wire                    ce_n,      // Chip enable (active low)
    input  wire                    we_n,      // Write enable (active low)
    input  wire [13:0]       addr,      // Address bus
    input  wire [7:0]        din,       // Data input
    output wire [7:0]        dout       // Data output
);

    // Address decoding
    // Upper bits select SRAM, lower bits address within SRAM
    wire [4:0] sram_sel;
    wire [8:0] sram_addr;

    assign sram_sel = addr[13:9];
    assign sram_addr = addr[8:0];

    // SRAM enable signals (directly from address decoder)
    wire [17:0] sram_ce_n;
    assign sram_ce_n[0] = ce_n | (sram_sel != 5'd0);
    assign sram_ce_n[1] = ce_n | (sram_sel != 5'd1);
    assign sram_ce_n[2] = ce_n | (sram_sel != 5'd2);
    assign sram_ce_n[3] = ce_n | (sram_sel != 5'd3);
    assign sram_ce_n[4] = ce_n | (sram_sel != 5'd4);
    assign sram_ce_n[5] = ce_n | (sram_sel != 5'd5);
    assign sram_ce_n[6] = ce_n | (sram_sel != 5'd6);
    assign sram_ce_n[7] = ce_n | (sram_sel != 5'd7);
    assign sram_ce_n[8] = ce_n | (sram_sel != 5'd8);
    assign sram_ce_n[9] = ce_n | (sram_sel != 5'd9);
    assign sram_ce_n[10] = ce_n | (sram_sel != 5'd10);
    assign sram_ce_n[11] = ce_n | (sram_sel != 5'd11);
    assign sram_ce_n[12] = ce_n | (sram_sel != 5'd12);
    assign sram_ce_n[13] = ce_n | (sram_sel != 5'd13);
    assign sram_ce_n[14] = ce_n | (sram_sel != 5'd14);
    assign sram_ce_n[15] = ce_n | (sram_sel != 5'd15);
    assign sram_ce_n[16] = ce_n | (sram_sel != 5'd16);
    assign sram_ce_n[17] = ce_n | (sram_sel != 5'd17);

    // SRAM output buses
    wire [7:0] sram_dout_0;
    wire [7:0] sram_dout_1;
    wire [7:0] sram_dout_2;
    wire [7:0] sram_dout_3;
    wire [7:0] sram_dout_4;
    wire [7:0] sram_dout_5;
    wire [7:0] sram_dout_6;
    wire [7:0] sram_dout_7;
    wire [7:0] sram_dout_8;
    wire [7:0] sram_dout_9;
    wire [7:0] sram_dout_10;
    wire [7:0] sram_dout_11;
    wire [7:0] sram_dout_12;
    wire [7:0] sram_dout_13;
    wire [7:0] sram_dout_14;
    wire [7:0] sram_dout_15;
    wire [7:0] sram_dout_16;
    wire [7:0] sram_dout_17;

    // SRAM macro instantiations
    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_0 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[0]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_0)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_1 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[1]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_1)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_2 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[2]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_2)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_3 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[3]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_3)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_4 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[4]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_4)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_5 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[5]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_5)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_6 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[6]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_6)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_7 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[7]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_7)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_8 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[8]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_8)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_9 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[9]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_9)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_10 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[10]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_10)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_11 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[11]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_11)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_12 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[12]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_12)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_13 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[13]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_13)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_14 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[14]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_14)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_15 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[15]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_15)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_16 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[16]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_16)
    );

    gf180mcu_fd_ip_sram__sram512x8m8wm1 sram_17 (
        `ifdef USE_POWER_PINS
        .VDD(VDD),
        .VSS(VSS),
        `endif
        .CLK(clk),
        .CEN(sram_ce_n[17]),
        .GWEN(we_n),
        .WEN(8'b0),  // All bits written when GWEN active
        .A(sram_addr),
        .D(din),
        .Q(sram_dout_17)
    );

    // Output multiplexer
    reg [7:0] dout_mux;

    always @(*) begin
        case (sram_sel)
            5'd0: dout_mux = sram_dout_0;
            5'd1: dout_mux = sram_dout_1;
            5'd2: dout_mux = sram_dout_2;
            5'd3: dout_mux = sram_dout_3;
            5'd4: dout_mux = sram_dout_4;
            5'd5: dout_mux = sram_dout_5;
            5'd6: dout_mux = sram_dout_6;
            5'd7: dout_mux = sram_dout_7;
            5'd8: dout_mux = sram_dout_8;
            5'd9: dout_mux = sram_dout_9;
            5'd10: dout_mux = sram_dout_10;
            5'd11: dout_mux = sram_dout_11;
            5'd12: dout_mux = sram_dout_12;
            5'd13: dout_mux = sram_dout_13;
            5'd14: dout_mux = sram_dout_14;
            5'd15: dout_mux = sram_dout_15;
            5'd16: dout_mux = sram_dout_16;
            5'd17: dout_mux = sram_dout_17;
            default: dout_mux = 8'h0;
        endcase
    end

    assign dout = dout_mux;

endmodule

`default_nettype wire